# Generated by Django 5.1.7 on 2026-06-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_mobile', models.CharField(max_length=15, verbose_name='Receiver Mobile Number')),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='Sender Mobile Number')),
                ('workTime', models.CharField(max_length=20, verbose_name='Work Time')),
                ('workUnit', models.CharField(max_length=10, verbose_name='Work Unit')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('workType', models.CharField(max_length=100, verbose_name='Work Type')),
                ('otherWork', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Work')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('request_date', models.CharField(max_length=20, verbose_name='Request Date')),
                ('preview_description', models.TextField(blank=True, null=True, verbose_name='Preview Description')),
                ('request_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Request Price')),
                ('preview_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Preview Date')),
            ],
        ),
        migrations.CreateModel(
            name='LandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='Sender Mobile Number')),
                ('landSize', models.CharField(max_length=50, verbose_name='Land Size')),
                ('period_start', models.DateField(verbose_name='Renting Period Start')),
                ('period_end', models.DateField(verbose_name='Renting Period End')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('receiver_mobile', models.CharField(max_length=15, verbose_name='Receiver Mobile Number')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('request_date', models.CharField(max_length=20, verbose_name='Request Date')),
                ('land_id', models.IntegerField(verbose_name='Land ID')),
                ('preview_description', models.TextField(blank=True, null=True, verbose_name='Preview Description')),
                ('request_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Request Price')),
                ('preview_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Preview Date')),
            ],
        ),
        migrations.CreateModel(
            name='MachineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sender Name')),
                ('sender_mobile', models.CharField(max_length=15, verbose_name='Sender Mobile Number')),
                ('hour', models.CharField(max_length=50, verbose_name='Hour')),
                ('period_start', models.DateField(verbose_name='Renting Period Start')),
                ('period_end', models.DateField(verbose_name='Renting Period End')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('machine_id', models.IntegerField(verbose_name='Machine ID')),
                ('machine_name', models.CharField(max_length=100, verbose_name='Machine Name')),
                ('receiver_mobile', models.CharField(max_length=15, verbose_name='Receiver Mobile (Owner)')),
                ('request_date', models.CharField(max_length=20, verbose_name='Request Date')),
                ('preview_description', models.TextField(blank=True, null=True, verbose_name='Preview Description')),
                ('request_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Request Price')),
                ('preview_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Preview Date')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='Razorpay Order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razorpay Payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Signature')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='created', max_length=20)),
                ('request_type', models.CharField(max_length=20, verbose_name='Request Type (Land, Labour, Machine)')),
                ('request_id', models.IntegerField(verbose_name='Associated Request ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
