# Generated by Django 5.1.7 on 2026-06-06 18:39

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('selected_state', models.CharField(max_length=100)),
                ('selected_district', models.CharField(max_length=100)),
                ('selected_village', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('Per Day', 'Per Day'), ('Per Hour', 'Per Hour')], max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('experience', models.IntegerField(default=0)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('LandSize', models.IntegerField()),
                ('TotalRentPrice', models.IntegerField()),
                ('RentPricePerAcre', models.IntegerField()),
                ('rentPeriod', models.IntegerField()),
                ('irrigationSource', models.CharField(max_length=100)),
                ('extraFacilities', models.CharField(max_length=200)),
                ('AccName', models.CharField(max_length=50)),
                ('BankName', models.CharField(max_length=50)),
                ('AccNo', models.CharField(max_length=20)),
                ('IFSC', models.CharField(max_length=20)),
                ('map_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('with_tractor', models.BooleanField(default=False)),
                ('tractor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('tractor_model', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_cost_acre', models.IntegerField()),
                ('hiring_cost_hour', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabourBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('b_account_no', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=20)),
                ('labour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='listings.labour')),
            ],
        ),
        migrations.CreateModel(
            name='LandPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.land')),
            ],
        ),
        migrations.CreateModel(
            name='MachineAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.machine')),
            ],
        ),
    ]
